apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: ntfy
  namespace: p2000-forwarder
spec:
  hosts:
  - "ntfy.nrkdci.net"
  gateways:
  - ntfy-gateway
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: ntfy.p2000-forwarder.svc.cluster.local
        port:
          number: 80
    timeout: 30s
    retries:
      attempts: 3
      perTryTimeout: 10s
      retryOn: 5xx,reset,connect-failure,refused-stream
